// const allSymbols=['1INCHUSDT', 'AAVEUSDT', 'ABUSDT', 'ABBCUSDT', 'ABYSSUSDT', 'ACEUSDT', 'ACHUSDT', 'ACSUSDT', 'ACTSOLUSDT', 'ADAUSDT', 'ADPUSDT', 'AEROUSDT', 'AEVOUSDT', 'AGIUSDT', 'AIUSDT', 'AIOZUSDT', 'AITECHUSDT', 'AIXBTUSDT', 'ALEUSDT', 'ALICEUSDT', 'ALIFUSDT', 'ALGOUSDT', 'ALPACAUSDT', 'ALTLAYERUSDT', 'ALTUSDT', 'AMPUSDT', 'ANDYUSDT', 'ANIMEUSDT', 'ANKRUSDT', 'APEUSDT', 'API3USDT', 'APUUSDT', 'ARBUSDT', 'ARKMUSDT', 'ATHUSDT', 'ATOMUSDT', 'ATTUSDT', 'AUCTIONUSDT', 'AUDIOUSDT', 'AVAUSDT', 'AVAXUSDT', 'AXLUSDT', 'AXSUSDT', 'BADGERUSDT', 'BAKEUSDT', 'BALUSDT', 'BANUSDT', 'BANANAUSDT', 'BANDUSDT', 'BATUSDT', 'BCDUSDT', 'BCHUSDT', 'BEAMUSDT', 'BETAUSDT', 'BGBUSDT', 'BICOUSDT', 'BIOUSDT', 'BLURUSDT', 'BMTUSDT', 'BNBUSDT', 'BNXNEWUSDT', 'BOMEUSDT', 'BONDUSDT', 'BONEUSDT', 'BOTXUSDT', 'BRETTUSDT', 'BSVUSDT', 'BTRNEWUSDT', 'CAKEUSDT', 'CATUSDT', 'CATIUSDT', 'CBGUSDT', 'CELUSDT', 'CELOUSDT', 'CELRUSDT', 'CGPTUSDT', 'CHEEMSUSDT', 'CHILLGUYUSDT', 'CHRUSDT', 'CHTUSDT', 'CHZUSDT', 'CKBUSDT', 'CNGUSDT', 'C98USDT', 'CLVUSDT', 'COLUSDT', 'COMPUSDT', 'CFXUSDT', 'CONXUSDT', 'COTIUSDT', 'CREAMUSDT', 'CROUSDT', 'CRVUSDT', 'CTCUSDT', 'CTKUSDT', 'CTSIUSDT', 'CVCUSDT', 'CVXUSDT', 'CYBERUSDT', 'DAIUSDT', 'DARUSDT', 'DCTUSDT', 'DEFIUSDT', 'DEGENUSDT', 'DENTUSDT', 'DEPUSDT', 'DEXEUSDT', 'DFGUSDT', 'DGBUSDT', 'DNTUSDT', 'DODOUSDT', 'DOGEUSDT', 'DOGE2USDT', 'DOGSUSDT', 'DOTUSDT', 'DRXUSDT', 'DUSKUSDT', 'DVIUSDT', 'EFIUSDT', 'EGLDUSDT', 'EIGENUSDT', 'ELFUSDT', 'ENAUSDT', 'ENJUSDT', 'ENSUSDT', 'EOSUSDT', 'ERNUSDT', 'ETCUSDT', 'ETHUSDT', 'ETHFIUSDT', 'EVERUSDT', 'FANCUSDT', 'FARTCOINUSDT', 'FETUSDT', 'FILUSDT', 'FLOKIUSDT', 'FLRUSDT', 'FLUXUSDT', 'FTMUSDT', 'FUELUSDT', 'FWOGUSDT', 'FXSUSDT', 'GALAGAMESUSDT', 'GAME2USDT', 'GICTUSDT', 'GIDUSDT', 'GIGAUSDT', 'GLCHUSDT', 'GLMUSDT', 'GMTUSDT', 'GMMTUSDT', 'GMXUSDT', 'GNOUSDT', 'GOATUSDT', 'GRASSUSDT', 'GRAVITYUSDT', 'GRIFFAINUSDT', 'GRTUSDT', 'GTCUSDT', 'GXCUSDT', 'H2OUSDT', 'HAEDALUSDT', 'HARTUSDT', 'HAPPYUSDT', 'HBARUSDT', 'HEDGUSDT', 'HFTUSDT', 'HIFIUSDT', 'HIGHUSDT', 'HIVEUSDT', 'HMSTRUSDT', 'HNSTUSDT', 'HNTUSDT', 'HONEYUSDT', 'HOTUSDT', 'HUMAUSDT', 'MYROUSDT', 'SPACEIDUSDT', 'ICPUSDT', 'IDXUSDT', 'ILVUSDT', 'IMXUSDT', 'INJUSDT', 'IOUSDT', 'IOSTUSDT', 'IOTAUSDT', 'IOTXUSDT', 'IQUSDT', 'ISLMUSDT', 'JASMYUSDT', 'JELLYJELLYUSDT', 'JOEUSDT', 'JUPUSDT', 'JSTUSDT', 'JTOUSDT', 'KAIAUSDT', 'KAITOUSDT', 'KDAGUSDT', 'KERNELUSDT', 'KMNOUSDT', 'KNCUSDT', 'KOKUSDT', 'KOMAUSDT', 'KRDUSDT', 'KSMUSDT', 'KUNCIUSDT', 'LDOUSDT', 'LEOUSDT', 'LEVERUSDT', 'LINKUSDT', 'LISTAUSDT', 'L3USDT', 'LADYSUSDT', 'LOOKSUSDT', 'LOOMUSDT', 'LPTUSDT', 'LQTYUSDT', 'LRCUSDT', 'LTCUSDT', 'LUNAUSDT', 'LUNCUSDT', 'LYFELUSDT', 'MAGICUSDT', 'MANAUSDT', 'MASKUSDT', 'MAVUSDT', 'MAVIAUSDT', 'MBOXUSDT', 'MCTUSDT', 'MEUSDT', 'MELANIAUSDT', 'MEMEUSDT', 'METAUSDT', 'METISUSDT', 'MEWUSDT', 'MILKUSDT', 'MKRUSDT', 'MNTUSDT', 'MOCAUSDT', 'MOGUSDT', 'MOODENGUSDT', 'MOONPIGUSDT', 'MOVEUSDT', 'MPROUSDT', 'MRSUSDT', 'MSHDUSDT', 'MTCUSDT', 'MTLUSDT', 'MULTIUSDT', 'MURAUSDT', 'NBTNEWUSDT', 'NEARUSDT', 'NEIROCTOUSDT', 'NEOUSDT', 'NEORPUSDT', 'NEONUSDT', 'NEXOUSDT', 'NFPUSDT', 'NPCUSDT', 'NRGUSDT', 'NUSAUSDT', 'OCTOUSDT', 'OGNUSDT', 'OKBUSDT', 'OMUSDT', 'OMGUSDT', 'OMNIUSDT', 'ONDOUSDT', 'ONTUSDT', 'OPUSDT', 'ORBSUSDT', 'ORCUSDT', 'ORCAUSDT', 'ORDERLYUSDT', 'PAXGUSDT', 'PENDLEUSDT', 'PENGUUSDT', 'PEOPLEUSDT', 'PEPEUSDT', 'PERPUSDT', 'PLUMEUSDT', 'GNSUSDT', 'PHAUSDT', 'PIXELUSDT', 'PNUTUSDT', 'POLSUSDT', 'POLUSDT', 'POLYUSDT', 'PONDUSDT', 'PONKEUSDT', 'PORTALUSDT', 'POPCATUSDT', 'POWRUSDT', 'PRCLUSDT', 'PRIMEUSDT', 'PROMUSDT', 'PUFFERUSDT', 'PYRUSDT', 'PYTHUSDT', 'QNTUSDT', 'RADUSDT', 'RAREUSDT', 'RAYUSDT', 'REDUSDT', 'RENUSDT', 'REPUSDT', 'REQUSDT', 'REZUSDT', 'RDNTUSDT', 'RLCUSDT', 'RENDERUSDT', 'ROOTUSDT', 'RPLUSDT', 'RSRUSDT', 'RSS3USDT', 'RVMUSDT', 'RVNUSDT', 'SANDUSDT', 'SAFEUSDT', 'SFIUSDT', 'SFPUSDT', 'SGTUSDT', 'SHANUSDT', 'SHIBUSDT', 'SHELLUSDT', 'SHREDUSDT', 'SIGNUSDT', 'SKLUSDT', 'SKYAUSDT', 'SLERFUSDT', 'SLPUSDT', 'SNTUSDT', 'SNXUSDT', 'SOLUSDT', 'SOLAYERUSDT', 'SOLVUSDT', 'SPELLUSDT', 'SPXUSDT', 'SRMUSDT', 'SSVUSDT', 'STGUSDT', 'STIKUSDT', 'STOUSDT', 'STORJUSDT', 'STRKUSDT', 'STRMUSDT', 'SUIUSDT', 'SUNUSDT', 'SUNDOGUSDT', 'SUPERVERSEUSDT', 'SUSHIUSDT', 'SYNUSDT', 'SYRUPUSDT', 'TAIKOUSDT', 'TELUSDT', 'TENUSDT', 'TFUELUSDT', 'THETAUSDT', 'THRESHOLDUSDT', 'TIAUSDT', 'TLMUSDT', 'TMGUSDT', 'TNSRUSDT', 'TOKENUSDT', 'TOKOUSDT', 'TONUSDT', 'TOSHIUSDT', 'TRBUSDT', 'TROLLSOLUSDT', 'TRUMPUSDT', 'TRXUSDT', 'TURBOUSDT', 'TUSDUSDT', 'TWELVEUSDT', 'UCJLUSDT', 'UMAUSDT', 'UNIUSDT', 'UNMDUSDT', 'USDCUSDT', 'USDTUSDT', 'UW3SUSDT', 'VANRYUSDT', 'VBGUSDT', 'VCGUSDT', 'VELOUSDT', 'VELODROMEUSDT', 'VETUSDT', 'VEXUSDT', 'VIDYXUSDT', 'VIRTUALSUSDT', 'VOXELUSDT', 'VRAUSDT', 'VSYSUSDT', 'W3FUSDT', 'W3S2USDT', 'WAVESUSDT', 'BTCUSDT','WBTCUSDT', 'WCTUSDT', 'WIFUSDT', 'WLDUSDT', 'WNXMUSDT', 'WOOUSDT', 'WORMHOLEUSDT', 'WOZXUSDT', 'WTECUSDT', 'XAUTUSDT', 'XCNUSDT', 'XDCUSDT', 'XGDUSDT', 'XEMUSDT', 'XLMUSDT', 'WEMIXUSDT', 'XRUSDT', 'XRPUSDT', 'XTZUSDT', 'XVSUSDT', 'YFIUSDT', 'YFIIUSDT', 'YGGUSDT', 'ZEREBROUSDT', 'ZETAUSDT', 'ZILUSDT', 'ZKJUSDT', 'ZORAUSDT', 'ZROUSDT', 'ZRXUSDT', 'BONKUSDT', 'BTTUSDT', 'KINUSDT', 'PUNDIXUSDT', 'XECUSDT', 'VIDYUSDT', 'VOLTUSDT']
// const top100Symbols = [
//   'BTC', 'ETH', 'XRP', 'BNB', 'SOL', 'USDC', 'DOGE', 'TRX', 'ADA',
//   'LINK', 'HYPE', 'XLM', 'SUI', 'BCH', 'HBAR', 'USDe', 'AVAX', 'LTC', 'TON',
//   'LEO', 'SHIB', 'UNI', 'DOT', 'OKB', 'CRO', 'DAI', 'BGB', 'ENA', 'AAVE',
//   'XMR', 'TAO', 'MNT', 'WBTC', 'WBETH', 'STETH', 'WSTETH', 'WETH', 'MATIC', 'ATOM', 'ICP', 'APT',
//   'FIL', 'TRB', 'CHZ', 'VET', 'NEAR', 'AXS', 'ALGO', 'FRAX', 'KMKR', 'CAKE',
//   'AURORA', 'XCN', 'SAND', 'MKR', 'RUNE', 'EGLD', 'FTM', 'FLOW', 'XTZ',
//   'GRT', 'LDO', 'KLAY', 'EOS', 'NEXO', 'ENJ', 'HNT', 'AR', 'ONE', 'THETA',
//   'ZEC', 'SNX', 'QNT', 'NEO', 'CELO', 'XTZ', 'DASH', 'ZIL', 'ZRX', 'BTG',
//   'YFI', 'COMP', 'OCEAN', 'SRM', 'RSR', 'UMA', 'BNT', 'KSM', 'GALA', 'XEM',
//   'ARDR', 'HOT', 'ANKR', 'GLM', 'IOST'
// ];
// const targetSymbols = top100Symbols.map(sym => sym + 'USDT');
// const fs = require('fs');
// const combinedSymbols = Array.from(new Set([...allSymbols, ...targetSymbols]));

// // 1. Ambil yang cocok
// let activeSymbols = combinedSymbols.filter(sym => targetSymbols.includes(sym));

// // 2. Tambah dari allSymbols sampai total 100
// if (activeSymbols.length < 100) {
//   const tambahan = combinedSymbols.filter(sym => !activeSymbols.includes(sym));
//   activeSymbols = [...activeSymbols, ...tambahan.slice(0, 100 - activeSymbols.length)];
// }
// // Pastikan hanya simbol yang ada di allSymbols dan ubah menjadi unik + potong ke 100
// const populerFiltered = Array.from(new Set(combinedSymbols.filter(s => activeSymbols.includes(s))))
//                             .slice(0, 100);

// const formatted = combinedSymbols.map(symbol => ({
//   symbol,
//   active: populerFiltered.includes(symbol)
// }));

// fs.writeFileSync('symbols.json', JSON.stringify(formatted, null, 2));
// console.log(`symbols.json di-generate: total ${formatted.length} simbol, ${populerFiltered.length} aktif.`);
// // // module.exports = {targetSymbols};